// Generated by CoffeeScript 1.6.3
/*
** Annotator {{VERSION}}
** https://github.com/okfn/annotator/
**
** Copyright 2012 {{AUTHORS}}.
** Dual licensed under the MIT and GPLv3 licenses.
** https://github.com/okfn/annotator/blob/master/LICENSE
**
** Built at: {{DATE}}
*/



/*
//@ sourceMappingURL=preamble.map
*/
